services:
  - type: web
    name: crop-health-backend
    env: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements-simple.txt && python -c "import nltk; nltk.download('punkt')"
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///crop_assistant.db
      - key: MAX_CONTENT_LENGTH
        value: 16777216
      - key: UPLOAD_FOLDER
        value: uploads
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: AGMARKNET_API_KEY
        sync: false
    autoDeploy: true 
