@echo off
echo Starting Crop Health & Agriculture Assistant...
echo.

echo Setting up backend...
cd backend
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Flask backend...
start python app.py
cd ..

echo.
echo Setting up frontend...
cd frontend
echo Starting frontend server...
start python -m http.server 8000
cd ..

echo.
echo Application is starting...
echo Backend: http://localhost:5000
echo Frontend: http://localhost:8000
echo.
echo Press any key to exit...
pause > nul 